services:
  - type: web
    name: banana-ai-assistant
    env: docker
    repo: https://github.com/bestpatcharapon/Banana_Ai_Assistant
    branch: API_Groq_Connect_mcp_server
    
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        value: "sqlite3:storage/production.sqlite3" # ใช้ SQLite แทน
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_SERVE_STATIC_FILES # ให้ Rails serve ไฟล์ my_tasks.html
        value: "true"
      
      # --- AI CONFIG ---
      - key: GROQ_API_KEY
        sync: false

      # --- AZURE DEVOPS CONFIG ---
      - key: AZURE_DEVOPS_ORGANIZATION
        value: bananacoding
      - key: AZURE_DEVOPS_PAT
        sync: false

      # --- MICROSOFT AUTH CONFIG ---
      - key: AZURE_TENANT_ID
        sync: false
      - key: AZURE_CLIENT_ID
        sync: false
      - key: AZURE_CLIENT_SECRET
        sync: false
